### ISSUE TITLE
Does not compile on Windows

### ISSUE THREAD

**Issue by dnicolodi** [c-util/c-siphash#3]
I'm trying to compile c-siphash on Windows, currently using MinGW-W64 although ideally I would like to support MSVC too. AFAIK c-siphash compiles just fine, however, it includes c-stdaux as a subproject and compiling c-stdaux tests fails because `pipe()` is not available. This is the build log from a Github Actions test runner:
```
[1/15] Compiling C object subprojects/libcstdaux-1/src/test-api.exe.p/test-api.c.obj
../../subprojects/libcstdaux-1/src/test-api.c: In function 'c_internal_hidden_fn':
../../subprojects/libcstdaux-1/src/test-api.c:15:55: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
   15 | _c_hidden_ int c_internal_hidden_fn(void) { return 0; }
      |                                                       ^
[2/15] Compiling C object subprojects/libcstdaux-1/src/test-basic.exe.p/test-basic.c.obj
../../subprojects/libcstdaux-1/src/test-basic.c: In function 'test_destructors':
../../subprojects/libcstdaux-1/src/test-basic.c:414:21: warning: implicit declaration of function 'pipe'; did you mean '_pipe'? [-Wimplicit-function-declaration]
  414 |                 r = pipe(tmp);
      |                     ^~~~
      |                     _pipe
../../subprojects/libcstdaux-1/src/test-basic.c:414:21: warning: nested extern declaration of 'pipe' [-Wnested-externs]
[3/15] Compiling C object subprojects/libcsiphash-1/src/libcsiphash-1-0.dll.p/c-siphash.c.obj
[4/15] Compiling C object subprojects/libcsiphash-1/src/test-basic.exe.p/test-basic.c.obj
[5/15] Linking target subprojects/libcstdaux-1/src/test-api.exe
[6/15] Linking target subprojects/libcstdaux-1/src/test-basic.exe
FAILED: subprojects/libcstdaux-1/src/test-basic.exe 
"gcc"  -o subprojects/libcstdaux-1/src/test-basic.exe subprojects/libcstdaux-1/src/test-basic.exe.p/test-basic.c.obj "-Wl,--allow-shlib-undefined" "-Wl,--subsystem,console" "-Wl,--start-group" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: subprojects/libcstdaux-1/src/test-basic.exe.p/test-basic.c.obj:test-basic.c:(.text.startup+0x16e): undefined reference to `pipe'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: subprojects/libcstdaux-1/src/test-basic.exe.p/test-basic.c.obj:test-basic.c:(.text.startup+0x1b0): undefined reference to `pipe'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: subprojects/libcstdaux-1/src/test-basic.exe.p/test-basic.c.obj:test-basic.c:(.text.startup+0x224): undefined reference to `pipe'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: subprojects/libcstdaux-1/src/test-basic.exe.p/test-basic.c.obj:test-basic.c:(.text.startup+0x27b): undefined reference to `pipe'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: subprojects/libcstdaux-1/src/test-basic.exe.p/test-basic.c.obj:test-basic.c:(.text.startup+0x2dc): undefined reference to `pipe'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: subprojects/libcstdaux-1/src/test-basic.exe.p/test-basic.c.obj:test-basic.c:(.text.startup+0x315): more undefined references to `pipe' follow
collect2.exe: error: ld returned 1 exit status
```
c-stdaux is used only to get the CFLAGS defined in that project, thus compiling it is in principle not required. However, I haven't found a way to disable it being compiled, or at least its test disabled.

Is Windows support something desirable? If so, what is the best way to solve this issue? I am not sure that rewriting the c-stdaux tests to be able to compile and run them on Windows makes sense only to get a project using c-siphash to compile.

**Comment by dvdhrm** [comment]
Yeah, we never really targeted Windows with c-utils. While technically most of the code is easily portable, it comes with many maintenance issues and nobody wanted to make the effort to maintain this. For instance, c-stdaux is also used for `_c_public_` annotations in c-siphash. While I know that all those bits have some equivalent on Windows, it is definitely a hassle to check it out for every new piece we add.

Also note that we use c-stdaux for build-time checks and build-integrations into bigger projects. In `c-list` we dropped `c-stdaux` as dependency to support Windows, but it now just means copying everything over into c-list whenever needed. I would very much like to avoid this.

In the end, I wouldn't mind porting c-stdaux to windows and getting some compile-time checks and disable specific tests or helpers. But if we do this, I really want to make sure to integrate it properly so the maintenance burden is not too high.

In the end, the easiest way out is to just copy the c-siphash code into your Windows project. But if you prefer working on c-stdaux, let me know and we can discuss Windows support over there. Due to c-list already supporting Windows, the CI integration should be straightforward.

**Comment by dnicolodi** [comment]
Thanks @dvdhrm I was looking at c-siphash to avoid to have another implementation of siphash. I don't know enough about development on Windows to be of any help in porting anything to Windows. I need a siphahsh implementation that compiles with MSVC for a python extension module. The c-siphash code is nice and well commented. I just copied it https://github.com/dnicolodi/python-siphash24

**Comment by dvdhrm** [comment]
I now split c-stdaux apart into separate modules and enabled CI on windows. Note that only a small subset of features is available on Windows, but this can be extended on demand.

I will now try to enable windows CI builds for c-siphash as well!

**Comment by dnicolodi** [comment]
Thanks @dvdhrm Please let me know if there is anything I can help with. At a quick glance, it seems that for `c-siphash` we will need `c-stdaux` to define `_c_always_inline_` for MSVC as well.

**Comment by dvdhrm** [comment]
Yup! All pushed now!

**Comment by dnicolodi** [comment]
Great! Thank you a lot!
